### ISSUE TITLE
Unknown error when submitting the DND results

### ISSUE THREAD

**Issue by YuanfeiHuang** [it-hao/ADFNet#1]
Dear author,

When I submit the denoised results (.mat) to DND submission server, there always raises an unknown error after uploading the .mat files. Have you encountered this type of problem? 
 
I'm looking forward to hearing back from you!

**Comment by it-hao** [comment]
> Dear author,
> 
> When I submit the denoised results (.mat) to DND submission server, there always raises an unknown error after uploading the .mat files. Have you encountered this type of problem?
> 
> I'm looking forward to hearing back from you!

根据MPRNet的代码和我代码中的[test_dnd_png.py](https://github.com/it-hao/ADFNet/blob/main/ADFNet_Real/test_dnd_png.py)，会产生50个.mat文件，然后上传过程可能会出现文件传输中断（或者你出现的那种错误）的情况，那样的话你可能需要重新选择未上传的那份文件继续上传。我的这个代码中没有提供预训练模型是因为我的那个模型和其他的弄混淆了，我电脑里只有得到的.mat文件，后续有时间我会重新训练一次，但是结果可能略有不同。

**Comment by YuanfeiHuang** [comment]
好像不是传输的问题，上传完之后会显示“unknown error”
![image](https://github.com/it-hao/ADFNet/assets/18394431/6575bab8-57b7-488f-88b8-2a06346820d8)
感觉特别奇怪，我尝试了好几种方法生成后的mat文件上传都有这个问题。

**Comment by it-hao** [comment]
> 



> 好像不是传输的问题，上传完之后会显示“unknown error” ![image](https://user-images.githubusercontent.com/18394431/248605287-6575bab8-57b7-488f-88b8-2a06346820d8.png) 感觉特别奇怪，我尝试了好几种方法生成后的mat文件上传都有这个问题。

那很奇怪，因为我昨晚还上传了一次手头的其他mat文件，出现了一两个mat文件像你那样的情况，然后我对这两个文件重传了，最终成功了的！
