### ISSUE TITLE
Which is the pre-training model for Real-world image?

### ISSUE THREAD

**Issue by Fan-QY** [it-hao/ADFNet#2]
Hello, First of all thank you for your contact work. Which pre-training model is for SIDD and DND data in Real-world image? Could you tell me please? I want to try inference directly.

**Comment by it-hao** [comment]
> Hello, First of all thank you for your contact work. Which pre-training model is for SIDD and DND data in Real-world image? Could you tell me please? I want to try inference directly.

Sorry, I lost the model for real denoising experiment in the process of sorting out the code, you can re-train according to the code we provided. Later, when I have time, I will retrain my model and update it to this site as needed.
