### ISSUE TITLE
卡在Making model... 终端窗口不能ctrl+c停止 只能关掉

### ISSUE THREAD

**Issue by hfw6310** [it-hao/ADFNet#5]
![image](https://github.com/it-hao/ADFNet/assets/38710029/c2d89ff8-2fea-42d5-b5c4-b057df260024) 请问一些博主 这个是驱动不对吗 我的GPU是3090

**Comment by it-hao** [comment]
> ![image](https://private-user-images.githubusercontent.com/38710029/293458120-c2d89ff8-2fea-42d5-b5c4-b057df260024.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM5NDM5MjEsIm5iZiI6MTcwMzk0MzYyMSwicGF0aCI6Ii8zODcxMDAyOS8yOTM0NTgxMjAtYzJkODlmZjgtMmZlYS00MmQ1LWI1YzQtYjA1N2RmMjYwMDI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjMwVDEzNDAyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMTMwMzZhN2Y0ODcyYmQwMTJlNDQ5ZGMyYjYyZjIyODAxMWM0ODcyM2Y5YTMxYTAwYWRjNjdkYWEyNzlkYjAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.n0FpZuqnRWgOCHviivSi-RgfpIguqPxU4mTNmy0ebug) 请问一些博主 这个是驱动不对吗 我的GPU是3090

这可能不是代码本身的问题
